#!/usr/bin/python
# -*- coding: utf-8
import sqlite3


db = sqlite3.connect('__musicdb.db')
c = db.cursor()
c.execute("SELECT artist, title, album, track_num, path FROM songs ORDER BY album")
print("|-------Artist-------+-------Title--------+-------Album--------+-№-+--------------------------------------Path--------------------------------------|")
for song in c.fetchall():
    print(f"|%20s|%20s|%20s|%3s|%80s|" % (song[0][:20], song[1][:20], song[2][:20], song[3], song[4][-80:]))
db.close()
