#!/usr/bin/python3
# -*- coding: utf-8
import sqlite3
db = sqlite3.connect('__musicdb.db')
c = db.cursor()
c.execute("SELECT artist, title, album, track_num, length, path FROM songs ORDER BY album")
print("|--------Artist--------+--------Title---------+--------Album---------+-№-+-Len-+------------------------------------Path-----------------------------------|")
for song in c.fetchall():
    print("|%22s|%22s|%22s|%3s|%5s|%75s|" % (song[0][:22], song[1][:22], song[2][:22], song[3], song[4], song[5][-75:]))
db.close()
